Closes #40 Key checking
jhampson-dbre/home_assistant pull request #41
Opened 2022-06-06 14:41 UTC by powerjc

Checks for existing keys on the controller and adds to home_assistant if found. Creates new keypair if both public and private keys are not found.

2022-06-07 22:20 UTC, jhampson-dbre requested changes
Left a couple of feedback. Let me know if you have any questions or need any help with the implementation.

2022-06-07 22:20 UTC, jhampson-dbre commented on roles/preinstall_config/tasks/main.yml
> +  register: existing_ssh_pubkey
Can we move loop over the private and public key to the first `stat` task? then in the copy task we can
```yaml
loop: "{{ existing_ssh_key.results }}"
loop_control:
  loop_var: key_file
when: key_file.stat.exists
```
After that, we should be able to remove `ignore_errors: '"Could not find" in result.msg'`

2022-06-07 22:20 UTC, jhampson-dbre commented on roles/preinstall_config/tasks/main.yml
> +  when: not existing_ssh_pubkey.stat.exists
Any concern with checking that both the private and public keys exist to determine when we should generate a new one key? If either are missing then I would think authentication would fail. do both key files exist on your system, or would it still cause issues for you if we generate a new key if `id_rsa` does not exist but `id_rsa.pub` does?

2022-06-13 15:20 UTC, powerjc commented on roles/preinstall_config/tasks/main.yml
> +  when: not existing_ssh_pubkey.stat.exists
Sorry for not getting back sooner. Thanks for engaging. Kludge would be a nice word for that ignore_errors statement. I was looking to find a way to handle having one file but not the other. I revved to more cleanly handle the one component situation, not very compact, but should do the trick. The loop to check option still had the chance to clobber an existing key component by my read.

2022-06-26 22:02 UTC, jhampson-dbre approved these changes
Looks good to me. I'm going to go ahead and merge and do some additional testing and try to get a release out soon! Thanks for your help!

2022-06-26 22:05 UTC, merged